#ifndef IEQUIP_VERSION_INCLUDED
#define IEQUIP_VERSION_INCLUDED

#define IEQUIP_VERSION_MAJOR		2
#define IEQUIP_VERSION_MINOR		4
#define IEQUIP_VERSION_PATCH		0
#define IEQUIP_VERSION_BETA			0
#define IEQUIP_VERSION_VERSTRING	"2, 4, 0, 0"

#endif
