#ifndef IEQUIP_VERSION_INCLUDED
#define IEQUIP_VERSION_INCLUDED

#define IEQUIP_MAKE_STR_HELPER(x) #x
#define IEQUIP_MAKE_STR(x) IEQUIP_MAKE_STR_HELPER(x)

#define IEQUIP_VERSION_MAJOR		2
#define IEQUIP_VERSION_MINOR		5
#define IEQUIP_VERSION_PATCH		0
#define IEQUIP_VERSION_BETA			0
#define IEQUIP_VERSION_VERSTRING	IEQUIP_MAKE_STR(IEQUIP_VERSION_MAJOR) "." IEQUIP_MAKE_STR(IEQUIP_VERSION_MINOR) "." IEQUIP_MAKE_STR(IEQUIP_VERSION_PATCH) "." IEQUIP_MAKE_STR(IEQUIP_VERSION_BETA)

#endif
